esphome:
  name: rele01
  friendly_name: Rele01

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "mQBiTcxCVGoy+8trsXqxSc1rqCTY1Y+hu8QO0FaEBm8="

ota:
  - platform: esphome
    password: "1fa77f1fb0368b14e08207d484568ddb"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Rele01 Fallback Hotspot"
    password: "BWNqskgU5hQf"

captive_portal:
    